name: lamakera
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_storage: ^2.0.3
  get: ^4.3.8
  flutter_local_notifications: ^15.1.0+1
  intl: ^0.18.1
  google_fonts: ^5.1.0
  date_picker_timeline: ^1.2.3
  sqflite: ^2.0.0+4
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^2.0.7
  rxdart: ^0.27.2
  timezone: ^0.9.2
  flutter_timezone: ^1.0.7
  intro_screen_onboarding_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/onboarding1.png
    - images/onboarding2.png
    - images/onboarding3.png
    - images/task.svg
    - images/tasktest.png
    - images/home.png
    - images/category.png

